services:
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    preBuildCommand: apt install libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 libffi-dev libjpeg-dev libopenjp2-7-dev
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT